export enum Eyebrow {
  ANGRY,
  ANGRY_NATURAL,
  NONE,
  DEFAULT_NATURAL,
  FLAT_NATURAL,
  RAISED_EXCITED,
  RAISED_EXCITED_NATURAL,
  SAD_CONCERNED,
  SAD_CONCERNED_NATURAL,
  UNIBROW_NATURAL,
  UPDOWN,
  UPDOWN_NATURAL,
}
